'use client'

import { useState } from 'react'
import { Activity, ArrowUpRight, Bell, Building2, CheckCircle2, ChevronDown, CircleDollarSign, ClipboardCheck, FileCheck2, FileText, LayoutDashboard, Menu, PanelLeftClose, PanelLeftOpen, Plus, Search, Settings, ShieldCheck, WalletCards, X } from 'lucide-react'

type View = 'overview' | 'contracts' | 'companies' | 'alerts' | 'payments' | 'documents' | 'validations' | 'audit'

const contracts = [
  ['CT-044-2026', 'Servicios integrales de tecnología', 'Nexa Sistemas S.A.S.', '$ 2.480.000.000', '68%', 'Activo', '18 mar 2027'],
  ['CT-067-2026', 'Operación y mantenimiento de red', 'Redes Andinas Ltda.', '$ 896.400.000', '42%', 'Por vencer', '24 nov 2026'],
  ['CT-031-2025', 'Suministro de insumos clínicos', 'Meditek Colombia S.A.', '$ 1.128.700.000', '91%', 'Activo', '08 ene 2027'],
  ['CT-019-2025', 'Interventoría de infraestructura', 'Control & Obra S.A.S.', '$ 574.200.000', '76%', 'Liquidación', '30 oct 2026'],
]

const nav = [
  { group: 'Espacio de trabajo', items: [['overview', 'Resumen', LayoutDashboard], ['contracts', 'Contratos', FileText], ['companies', 'Empresas', Building2]] },
  { group: 'Control operativo', items: [['alerts', 'Alertas', Bell], ['payments', 'Pagos y ejecución', WalletCards], ['documents', 'Documentos', FileCheck2], ['validations', 'Validaciones', ClipboardCheck]] },
  { group: 'Trazabilidad', items: [['audit', 'Bitácora de auditoría', ShieldCheck]] },
] as const

function Logo() { return <div className="brand"><span className="brand-mark">+</span><span><b>nexo</b><small>control contractual</small></span></div> }
function Badge({ children }: { children: string }) { return <span className={`badge ${children === 'Activo' ? 'good' : children === 'Por vencer' ? 'warn' : children === 'Liquidación' ? 'neutral' : 'bad'}`}><i />{children}</span> }
function Header({ title, eyebrow, text, action }: { title: string; eyebrow: string; text: string; action?: React.ReactNode }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</div> }
function Kpi({ icon: Icon, label, value, delta, accent = false }: { icon: typeof Activity; label: string; value: string; delta: string; accent?: boolean }) { return <article className={`kpi ${accent ? 'accent-card' : ''}`}><div className="kpi-label"><span>{label}</span><Icon /></div><strong>{value}</strong><small><span className="delta"><ArrowUpRight />{delta}</span> vs. mes anterior</small></article> }
function Chart() { return <div className="chart"><div className="chart-axis"><span>$ 8,2B</span><span>$ 6,1B</span><span>$ 4,0B</span><span>$ 1,8B</span></div><svg viewBox="0 0 640 190" preserveAspectRatio="none" aria-label="Ejecución acumulada"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#c8ef36" stopOpacity=".3"/><stop offset="1" stopColor="#c8ef36" stopOpacity="0"/></linearGradient></defs><path d="M0 155 C55 145 76 132 112 144 S175 112 216 126 S268 93 305 108 S356 72 394 84 S447 61 488 72 S540 38 578 50 S615 24 640 31 V190 H0Z" fill="url(#fill)"/><path d="M0 155 C55 145 76 132 112 144 S175 112 216 126 S268 93 305 108 S356 72 394 84 S447 61 488 72 S540 38 578 50 S615 24 640 31" fill="none" stroke="#c8ef36" strokeWidth="3" /></svg><div className="chart-months"><span>ENE</span><span>FEB</span><span>MAR</span><span>ABR</span><span>MAY</span><span>JUN</span><span>JUL</span><span>AGO</span><span>SEP</span><span>OCT</span></div></div> }
function Table() { return <div className="table-wrap"><div className="toolbar"><label><Search /><input placeholder="Buscar contrato, empresa..." /></label><button className="outline-btn">Filtrar</button><button className="outline-btn">Exportar</button></div><table><thead><tr><th>Contrato</th><th>Responsable</th><th>Valor actualizado</th><th>Ejecución</th><th>Estado</th><th>Vencimiento</th></tr></thead><tbody>{contracts.map(([id, title, company, value, progress, status, due]) => <tr key={id}><td><b>{id}</b><span>{title}</span></td><td><span className="avatar">LM</span>Laura Méndez</td><td className="money">{value}</td><td><div className="progress"><i style={{ width: progress }} /></div><small>{progress}</small></td><td><Badge>{status}</Badge></td><td className="muted">{due}</td></tr>)}</tbody></table></div> }
function Dashboard({ go }: { go: (v: View) => void }) { return <><Header eyebrow="Miércoles, 1 de octubre de 2026" title="Buenos días, Laura" text="Este es el pulso de tu operación contractual." action={<button className="primary-btn" onClick={() => go('contracts')}><Plus /> Nuevo contrato</button>} /><div className="kpi-grid"><Kpi icon={CircleDollarSign} label="Valor bajo gestión" value="$ 12,8B" delta="+8,4%" accent /><Kpi icon={FileText} label="Contratos activos" value="24" delta="+3" /><Kpi icon={Bell} label="Alertas por atender" value="7" delta="+18,2%" /><Kpi icon={Activity} label="Ejecución promedio" value="74,6%" delta="+4,8%" /></div><div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Ejecución acumulada</h2><p>Valor ejecutado por mes · 2026</p></div><button className="select">Últimos 10 meses <ChevronDown /></button></div><Chart /></section><section className="panel health"><div className="panel-head"><div><h2>Salud contractual</h2><p>Distribución del portafolio</p></div></div><div className="ring"><strong>82</strong><span>/ 100</span></div><b>Operación saludable</b><small>+6 puntos este mes</small><div className="legend"><span><i className="lime" />En control <b>17</b></span><span><i className="amber" />Requieren atención <b>5</b></span><span><i className="red" />Riesgo crítico <b>2</b></span></div></section></div><section className="panel"><div className="panel-head"><div><h2>Contratos prioritarios</h2><p>Los que requieren una acción esta semana</p></div><button className="link-btn" onClick={() => go('contracts')}>Ver todos <ArrowUpRight /></button></div><Table /></section></> }
function Module({ view }: { view: View }) { const names: Record<string, [string, string]> = { companies: ['Empresas', 'Entidades, proveedores y responsables vinculados al sistema.'], alerts: ['Alertas', 'Prioriza los riesgos y vencimientos antes de que ocurran.'], payments: ['Pagos y ejecución', 'Conciliación financiera y avance real del portafolio.'], documents: ['Documentos', 'Versiona, consulta y protege cada soporte contractual.'], validations: ['Validaciones', 'Encuentra inconsistencias y fortalece el control interno.'], audit: ['Bitácora de auditoría', 'Un registro inmutable de cada cambio relevante.'] }; const [title, text] = names[view] || names.companies; return <><Header eyebrow="Centro de control" title={title} text={text} action={<button className="primary-btn"><Plus /> Nueva acción</button>} /><section className="panel empty-module"><CheckCircle2 /><h2>{title} en un solo lugar</h2><p>El módulo está listo para conectar tus procesos, equipos y expedientes con trazabilidad completa.</p><button className="outline-btn">Explorar módulo</button></section></> }
function Login({ onLogin }: { onLogin: () => void }) { const [loading, setLoading] = useState(false); return <main className="login"><section className="login-visual"><div><Logo /><span className="platform">PLATAFORMA 2026</span></div><div className="hero-copy"><span className="eyebrow">Control que conecta</span><h1>Contratos claros.<br /><em>Decisiones seguras.</em></h1><p>Nexo convierte la gestión contractual en una operación visible, trazable y lista para avanzar.</p></div><div className="live-card"><span><i /> Operación en vivo</span><b>Portafolio bajo control</b><strong>$ 12,8B</strong><small><ArrowUpRight /> +8,4% este mes · 24 contratos activos</small></div></section><section className="login-side"><div className="login-box"><span className="eyebrow">Bienvenido de vuelta</span><h2>Entra a tu espacio</h2><p>Usa tus credenciales para continuar con tu operación.</p><form onSubmit={(e) => { e.preventDefault(); setLoading(true); setTimeout(onLogin, 350) }}><label>Correo corporativo<input type="email" defaultValue="laura@nexo.co" required /></label><label>Contraseña<input type="password" defaultValue="nexo2026" required /></label><div className="form-row"><label><input type="checkbox" defaultChecked /> Recordarme</label><a href="#">¿Olvidaste tu contraseña?</a></div><button className="primary-btn full" disabled={loading}>{loading ? 'Ingresando...' : 'Ingresar al espacio'} <ArrowUpRight /></button></form><small className="secure"><ShieldCheck /> Acceso protegido y cifrado de extremo a extremo</small></div></section></main> }
export default function Page() { const [logged, setLogged] = useState(false); const [view, setView] = useState<View>('overview'); const [collapsed, setCollapsed] = useState(false); const [mobile, setMobile] = useState(false); const go = (v: View) => { setView(v); setMobile(false) }; if (!logged) return <Login onLogin={() => setLogged(true)} />; return <div className="app"><aside className={`sidebar ${collapsed ? 'collapsed' : ''} ${mobile ? 'open' : ''}`}><div className="side-top"><Logo /><button onClick={() => setCollapsed(!collapsed)} aria-label="Colapsar menú">{collapsed ? <PanelLeftOpen /> : <PanelLeftClose />}</button></div><nav>{nav.map(section => <div className="nav-section" key={section.group}><small>{section.group}</small>{section.items.map(([id, label, Icon]) => <button className={view === id ? 'active' : ''} key={id} onClick={() => go(id as View)}><Icon /><span>{label}</span>{id === 'contracts' && <b>24</b>}{id === 'alerts' && <b>7</b>}</button>)}</div>)}</nav><div className="side-bottom"><button><Settings /><span>Configuración</span></button><div className="profile"><span>LM</span><div><b>Laura Méndez</b><small>Administradora</small></div><ChevronDown /></div></div></aside>{mobile && <button className="scrim" aria-label="Cerrar menú" onClick={() => setMobile(false)} />}<main className="content"><header className="topbar"><button className="mobile-trigger" onClick={() => setMobile(true)}><Menu /></button><div className="crumb">Espacio de trabajo <span>/</span> <b>{view === 'overview' ? 'Resumen' : view}</b></div><div className="top-actions"><button aria-label="Buscar"><Search /></button><button aria-label="Notificaciones"><Bell /><i /></button><span className="top-avatar">LM</span></div></header><div className="page">{view === 'overview' ? <Dashboard go={go} /> : view === 'contracts' ? <><Header eyebrow="Registro contractual" title="Contratos" text="Administra el ciclo de vida completo de tus acuerdos." action={<button className="primary-btn"><Plus /> Nuevo contrato</button>} /><section className="panel"><Table /></section></> : <Module view={view} />}</div></main></div> }
