import {
  Mail,
  Phone,
  PieChart,
  Briefcase,
  Hourglass,
  CalendarDays,
  Building2,
  FileSignature,
  Network,
  ListChecks,
  TrendingUp,
  Wallet,
  Shield,
  Umbrella,
  FolderTree,
  FileCode2,
  GitCompare,
  Bell,
  Flame,
  Gavel,
  Fingerprint,
  FileOutput,
  Settings,
  Search,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Info,
  ChevronRight,
  ChevronLeft,
  House,
  Map,
  Scale,
  ClipboardCheck,
  ChevronDown,
  Menu,
  User,
  Plus,
  Trash2,
  Edit,
  Download,
  Upload,
  Play,
  Pause,
  Printer,
  FileSpreadsheet,
  FileText,
  Clock,
  Lock,
  Layers,
  HelpCircle,
  Eye,
  X,
  ExternalLink,
  MapPin,
  Calendar,
  // UI PASS agy-expediente: iconografía del expediente (header, pestañas, secciones)
  Gauge,
  ScrollText,
  Package,
  CirclePause,
  CalendarPlus,
  CalendarClock,
  Coins,
  Receipt,
  Ellipsis,
  Activity,
  Ban,
  Users,
  UserCheck,
  Hash,
  ShieldCheck,
  // UI PASS agy-tabs1
  Percent,
  BarChart3,
  PlusCircle,
  MinusCircle,
  // UI PASS agy-tabs2
  Paperclip,
  List,
  CirclePlay,
  OctagonAlert
} from 'lucide-react';

export const Icon = ({
  name,
  className,
  style,
  size
}: {
  name: string;
  className?: string;
  style?: React.CSSProperties;
  size?: number;
}) => {
  const cleanName = (name || '').replace(/^fa-/, '').toLowerCase();
  const map: Record<string, any> = {
    'envelope': Mail,
    'phone': Phone,
    'chart-pie': PieChart,
    'briefcase': Briefcase,
    'hourglass': Hourglass,
    'hourglass-half': Hourglass,
    'calendar-days': CalendarDays,
    'calendar': Calendar,
    'building': Building2,
    'file-contract': FileSignature,
    'sitemap': Network,
    'list-check': ListChecks,
    'chart-line': TrendingUp,
    'money-check-dollar': Wallet,
    'shield': Shield,
    'shield-halved': Shield,
    'umbrella': Umbrella,
    'folder-tree': FolderTree,
    'folder': FolderTree,
    'file-signature': FileSignature,
    'code-compare': GitCompare,
    'bell': Bell,
    'fire': Flame,
    'gavel': Gavel,
    'fingerprint': Fingerprint,
    'file-export': FileOutput,
    'gear': Settings,
    'cog': Settings,
    'settings': Settings,
    'search': Search,
    'plus': Plus,
    'trash': Trash2,
    'edit': Edit,
    'pen': Edit,
    'pen-to-square': Edit,
    'download': Download,
    'upload': Upload,
    'play': Play,
    'pause': Pause,
    'print': Printer,
    'file-excel': FileSpreadsheet,
    'file-pdf': FileText,
    'file-text': FileText,
    'clock': Clock,
    'lock': Lock,
    'layers': Layers,
    'bars': Menu,
    'menu': Menu,
    'user': User,
    'home': House,
    'chevron-left': ChevronLeft,
    'diagram-project': Network,
    'history': Fingerprint,
    'file-chart': FileOutput,
    'file-spreadsheet': FileSpreadsheet,
    'file-csv': FileSpreadsheet,
    'printer': Printer,
    'dollar-sign': Wallet,
    'trending-up': TrendingUp,
    'alert-triangle': AlertTriangle,
    'shield-alert': Shield,
    'map': Map,
    'scale-balanced': Scale,
    'clipboard-check': ClipboardCheck,
    'x': X,
    'check': CheckCircle2,
    'check-circle': CheckCircle2,
    'circle-check': CheckCircle2,
    'triangle-exclamation': AlertTriangle,
    'exclamation-triangle': AlertTriangle,
    'circle-exclamation': AlertCircle,
    'exclamation-circle': AlertCircle,
    'alert-circle': AlertCircle,
    'info': Info,
    'info-circle': Info,
    'circle-info': Info,
    'chevron-right': ChevronRight,
    'chevron-down': ChevronDown,
    'eye': Eye,
    'close': X,
    'xmark': X,
    'circle-xmark': X,
    'external-link': ExternalLink,
    'map-location-dot': MapPin,
    'map-pin': MapPin,
    'question': HelpCircle,
    'file-circle-question': HelpCircle,
    // UI PASS agy-expediente
    'gauge': Gauge,
    'scroll-text': ScrollText,
    'package': Package,
    'circle-pause': CirclePause,
    'calendar-plus': CalendarPlus,
    'calendar-clock': CalendarClock,
    'coins': Coins,
    'receipt': Receipt,
    'wallet': Wallet,
    'ellipsis': Ellipsis,
    'activity': Activity,
    'ban': Ban,
    'users': Users,
    'user-check': UserCheck,
    'hash': Hash,
    'shield-check': ShieldCheck,
    // UI PASS agy-tabs1
    'pencil': Edit,
    'percent': Percent,
    'bar-chart': BarChart3,
    'bar-chart-2': BarChart3,
    'plus-circle': PlusCircle,
    'minus-circle': MinusCircle,
    // UI PASS agy-tabs2
    'paperclip': Paperclip,
    'list': List,
    'pause-circle': CirclePause,
    'play-circle': CirclePlay,
    'alert-octagon': OctagonAlert
  };

  const Component = map[cleanName] || Info;
  return <Component className={`icon ${className || ''}`} size={size || 16} style={style} />;
};
