import {
  PieChart,
  Briefcase,
  Hourglass,
  CalendarDays,
  Building2,
  FileSignature,
  Network,
  ListChecks,
  TrendingUp,
  Wallet,
  Shield,
  Umbrella,
  FolderTree,
  FileCode2,
  GitCompare,
  Bell,
  Flame,
  Gavel,
  Fingerprint,
  FileOutput,
  Settings,
  Search,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Info,
  ChevronRight,
  ChevronDown,
  Menu,
  User,
  Plus,
  Trash2,
  Edit,
  Download,
  Upload,
  Play,
  Pause,
  Printer,
  FileSpreadsheet,
  FileText,
  Clock,
  Lock,
  Layers,
  HelpCircle,
  Eye,
  X,
  ExternalLink,
  MapPin,
  Calendar
} from 'lucide-react';

export const Icon = ({ name, className }: { name: string; className?: string }) => {
  const cleanName = (name || '').replace(/^fa-/, '').toLowerCase();
  const map: Record<string, any> = {
    'chart-pie': PieChart,
    'briefcase': Briefcase,
    'hourglass': Hourglass,
    'hourglass-half': Hourglass,
    'calendar-days': CalendarDays,
    'calendar': Calendar,
    'building': Building2,
    'file-contract': FileSignature,
    'sitemap': Network,
    'list-check': ListChecks,
    'chart-line': TrendingUp,
    'money-check-dollar': Wallet,
    'shield': Shield,
    'shield-halved': Shield,
    'umbrella': Umbrella,
    'folder-tree': FolderTree,
    'folder': FolderTree,
    'file-signature': FileSignature,
    'code-compare': GitCompare,
    'bell': Bell,
    'fire': Flame,
    'gavel': Gavel,
    'fingerprint': Fingerprint,
    'file-export': FileOutput,
    'gear': Settings,
    'cog': Settings,
    'settings': Settings,
    'search': Search,
    'plus': Plus,
    'trash': Trash2,
    'edit': Edit,
    'pen': Edit,
    'pen-to-square': Edit,
    'download': Download,
    'upload': Upload,
    'play': Play,
    'pause': Pause,
    'print': Printer,
    'file-excel': FileSpreadsheet,
    'file-pdf': FileText,
    'file-text': FileText,
    'clock': Clock,
    'lock': Lock,
    'layers': Layers,
    'bars': Menu,
    'menu': Menu,
    'user': User,
    'home': PieChart,
    'check': CheckCircle2,
    'check-circle': CheckCircle2,
    'circle-check': CheckCircle2,
    'triangle-exclamation': AlertTriangle,
    'exclamation-triangle': AlertTriangle,
    'circle-exclamation': AlertCircle,
    'exclamation-circle': AlertCircle,
    'alert-circle': AlertCircle,
    'info': Info,
    'info-circle': Info,
    'circle-info': Info,
    'chevron-right': ChevronRight,
    'chevron-down': ChevronDown,
    'eye': Eye,
    'close': X,
    'xmark': X,
    'circle-xmark': X,
    'external-link': ExternalLink,
    'map-location-dot': MapPin,
    'map-pin': MapPin,
    'question': HelpCircle,
    'file-circle-question': HelpCircle
  };

  const Component = map[cleanName] || Info;
  return <Component className={`icon ${className || ''}`} size={16} />;
};
